<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.irrva6T' shared service.

return $this->privates['.service_locator.irrva6T'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'data' => ['privates', '.errored..service_locator.irrva6T.App\\Entity\\MemberTask', NULL, 'Cannot autowire service ".service_locator.irrva6T": it references class "App\\Entity\\MemberTask" but no such service exists.'],
    'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'partner' => ['privates', '.errored..service_locator.irrva6T.Symfony\\Component\\Security\\Core\\User\\UserInterface', NULL, 'Cannot autowire service ".service_locator.irrva6T": it references interface "Symfony\\Component\\Security\\Core\\User\\UserInterface" but no such service exists. Did you create a class that implements this interface?'],
], [
    'data' => 'App\\Entity\\MemberTask',
    'em' => '?',
    'partner' => 'Symfony\\Component\\Security\\Core\\User\\UserInterface',
]);
