<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.rZZ2Fol' shared service.

return $this->privates['.service_locator.rZZ2Fol'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'mailer' => ['services', 'swiftmailer.mailer.default', 'getSwiftmailer_Mailer_DefaultService.php', true],
    'params' => ['privates', 'parameter_bag', 'getParameterBagService', false],
    'partnerRepository' => ['privates', 'App\\Repository\\PartnerRepository', 'getPartnerRepositoryService.php', true],
    'validator' => ['privates', 'api_platform.validator', 'getApiPlatform_ValidatorService.php', true],
], [
    'em' => '?',
    'mailer' => '?',
    'params' => '?',
    'partnerRepository' => 'App\\Repository\\PartnerRepository',
    'validator' => '?',
]);
