<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ZP90jWn' shared service.

return $this->privates['.service_locator.ZP90jWn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'ngoalsRepository' => ['privates', 'App\\Repository\\NGoalsRepository', 'getNGoalsRepositoryService.php', true],
], [
    'ngoalsRepository' => 'App\\Repository\\NGoalsRepository',
]);
