<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.rXDK.J5' shared service.

return $this->privates['.service_locator.rXDK.J5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'npersonalityStyleTranslationRepository' => ['privates', 'App\\Repository\\NPersonalityStyleTranslationRepository', 'getNPersonalityStyleTranslationRepositoryService.php', true],
], [
    'npersonalityStyleTranslationRepository' => 'App\\Repository\\NPersonalityStyleTranslationRepository',
]);
