<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.OFDSx0N' shared service.

return $this->privates['.service_locator.OFDSx0N'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'ncomplimentRepository' => ['privates', 'App\\Repository\\NComplimentRepository', 'getNComplimentRepositoryService.php', true],
], [
    'ncomplimentRepository' => 'App\\Repository\\NComplimentRepository',
]);
