<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\Languages\LanguagesFrontendGetCollectionAction' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Controller/Languages/LanguagesFrontendGetCollectionAction.php';

return $this->services['App\\Controller\\Languages\\LanguagesFrontendGetCollectionAction'] = new \App\Controller\Languages\LanguagesFrontendGetCollectionAction(($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()));
