<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.PoKAg3i.App\Entity\MemberProjects' shared service.

$this->throw('Cannot autowire service ".service_locator.PoKAg3i": it references class "App\\Entity\\MemberProjects" but no such service exists.');
