<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.8rTI.Ck.App\Entity\MemberTask' shared service.

$this->throw('Cannot autowire service ".service_locator.8rTI.Ck": it references class "App\\Entity\\MemberTask" but no such service exists.');
