<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.FgUPP4D.App\Entity\MemberGoals' shared service.

$this->throw('Cannot autowire service ".service_locator.FgUPP4D": it references class "App\\Entity\\MemberGoals" but no such service exists.');
