<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.J0Kf9DR.App\Entity\Partner' shared service.

$this->throw('Cannot autowire service ".service_locator.J0Kf9DR": it references class "App\\Entity\\Partner" but no such service exists.');
