<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\Partner\PartnerInsertNotificationAction' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Controller/Partner/PartnerInsertNotificationAction.php';

return $this->services['App\\Controller\\Partner\\PartnerInsertNotificationAction'] = new \App\Controller\Partner\PartnerInsertNotificationAction();
