<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.access_map' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/AccessMapInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/AccessMap.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/http-foundation/RequestMatcherInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/http-foundation/RequestMatcher.php';

$this->privates['security.access_map'] = $instance = new \Symfony\Component\Security\Http\AccessMap();

$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/login'), [0 => 'IS_AUTHENTICATED_ANONYMOUSLY'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/frontend/profile'), [0 => 'ROLE_CLIENT'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/frontend/member/profile'), [0 => 'ROLE_MEMBER'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/frontend/partners'), [0 => 'IS_AUTHENTICATED_FULLY'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/frontend/supervisors'), [0 => 'IS_AUTHENTICATED_FULLY'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/frontend/partner/profile'), [0 => 'ROLE_PARTNER'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/frontend/supervisor/profile'), [0 => 'ROLE_SUPERVISOR'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/frontend'), [0 => 'IS_AUTHENTICATED_ANONYMOUSLY'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/'), [0 => 'ROLE_USER'], NULL);

return $instance;
