<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\NPreferredTime\NPreferredTimeFrontendGetItemAction' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Controller/NPreferredTime/NPreferredTimeFrontendGetItemAction.php';

return $this->services['App\\Controller\\NPreferredTime\\NPreferredTimeFrontendGetItemAction'] = new \App\Controller\NPreferredTime\NPreferredTimeFrontendGetItemAction();
