<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.AxNwmLx' shared service.

return $this->privates['.service_locator.AxNwmLx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'ndaysTranslationRepository' => ['privates', 'App\\Repository\\NDaysTranslationRepository', 'getNDaysTranslationRepositoryService.php', true],
], [
    'ndaysTranslationRepository' => 'App\\Repository\\NDaysTranslationRepository',
]);
