<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.PoKAg3i' shared service.

return $this->privates['.service_locator.PoKAg3i'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'data' => ['privates', '.errored..service_locator.PoKAg3i.App\\Entity\\MemberProjects', NULL, 'Cannot autowire service ".service_locator.PoKAg3i": it references class "App\\Entity\\MemberProjects" but no such service exists.'],
    'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'member' => ['privates', '.errored..service_locator.PoKAg3i.Symfony\\Component\\Security\\Core\\User\\UserInterface', NULL, 'Cannot autowire service ".service_locator.PoKAg3i": it references interface "Symfony\\Component\\Security\\Core\\User\\UserInterface" but no such service exists. Did you create a class that implements this interface?'],
], [
    'data' => 'App\\Entity\\MemberProjects',
    'em' => '?',
    'member' => 'Symfony\\Component\\Security\\Core\\User\\UserInterface',
]);
