<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.hP_oWeV' shared service.

return $this->privates['.service_locator.hP_oWeV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'nspecicOutcomeTranslationRepository' => ['privates', 'App\\Repository\\NSpecicOutcomeTranslationRepository', 'getNSpecicOutcomeTranslationRepositoryService.php', true],
], [
    'nspecicOutcomeTranslationRepository' => 'App\\Repository\\NSpecicOutcomeTranslationRepository',
]);
