<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doctrine.fixtures_load_command' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/Command/DoctrineCommand.php';
include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/Command/LoadDataFixturesDoctrineCommand.php';
include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Loader.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/doctrine-bridge/DataFixtures/ContainerAwareLoader.php';
include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/Loader/SymfonyFixturesLoader.php';
include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/FixtureInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/SharedFixtureInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/AbstractFixture.php';
include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/ORMFixtureInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/Fixture.php';
include_once \dirname(__DIR__, 4).'/src/DataFixtures/AvailableFixtures.php';
include_once \dirname(__DIR__, 4).'/src/DataFixtures/ComplimentFixtures.php';
include_once \dirname(__DIR__, 4).'/src/DataFixtures/DaysFixtures.php';
include_once \dirname(__DIR__, 4).'/src/DataFixtures/FeedbackFixtures.php';
include_once \dirname(__DIR__, 4).'/src/DataFixtures/LevelUrgencyFixtures.php';
include_once \dirname(__DIR__, 4).'/src/DataFixtures/PersonalityStyleFixtures.php';
include_once \dirname(__DIR__, 4).'/src/DataFixtures/PreferredTimeFixtures.php';
include_once \dirname(__DIR__, 4).'/src/DataFixtures/SpecicOutcomeFixtures.php';
include_once \dirname(__DIR__, 4).'/src/DataFixtures/GoalsFixtures.php';
include_once \dirname(__DIR__, 4).'/src/DataFixtures/TaskFixtures.php';
include_once \dirname(__DIR__, 4).'/src/DataFixtures/RoleFixtures.php';
include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/DependentFixtureInterface.php';
include_once \dirname(__DIR__, 4).'/src/DataFixtures/UserFixtures.php';

$a = new \Doctrine\Bundle\FixturesBundle\Loader\SymfonyFixturesLoader($this);
$a->addFixtures([0 => ['fixture' => new \App\DataFixtures\AvailableFixtures(), 'groups' => []], 1 => ['fixture' => new \App\DataFixtures\ComplimentFixtures(), 'groups' => []], 2 => ['fixture' => new \App\DataFixtures\DaysFixtures(), 'groups' => []], 3 => ['fixture' => new \App\DataFixtures\FeedbackFixtures(), 'groups' => []], 4 => ['fixture' => new \App\DataFixtures\LevelUrgencyFixtures(), 'groups' => []], 5 => ['fixture' => new \App\DataFixtures\PersonalityStyleFixtures(), 'groups' => []], 6 => ['fixture' => new \App\DataFixtures\PreferredTimeFixtures(), 'groups' => []], 7 => ['fixture' => new \App\DataFixtures\SpecicOutcomeFixtures(), 'groups' => []], 8 => ['fixture' => new \App\DataFixtures\GoalsFixtures(), 'groups' => []], 9 => ['fixture' => new \App\DataFixtures\TaskFixtures(), 'groups' => []], 10 => ['fixture' => new \App\DataFixtures\RoleFixtures(), 'groups' => []], 11 => ['fixture' => new \App\DataFixtures\UserFixtures(($this->services['security.password_encoder'] ?? $this->load('getSecurity_PasswordEncoderService.php'))), 'groups' => []]]);

$this->privates['doctrine.fixtures_load_command'] = $instance = new \Doctrine\Bundle\FixturesBundle\Command\LoadDataFixturesDoctrineCommand($a, ($this->services['doctrine'] ?? $this->getDoctrineService()));

$instance->setName('doctrine:fixtures:load');

return $instance;
