<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\NAvailable\NAvailableFrontendGetItemAction' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Controller/NAvailable/NAvailableFrontendGetItemAction.php';

return $this->services['App\\Controller\\NAvailable\\NAvailableFrontendGetItemAction'] = new \App\Controller\NAvailable\NAvailableFrontendGetItemAction();
