<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\NSpecicOutcome\NSpecicOutcomeFrontendGetItemAction' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Controller/NSpecicOutcome/NSpecicOutcomeFrontendGetItemAction.php';

return $this->services['App\\Controller\\NSpecicOutcome\\NSpecicOutcomeFrontendGetItemAction'] = new \App\Controller\NSpecicOutcome\NSpecicOutcomeFrontendGetItemAction();
