<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\NFeedback\NFeedbackFrontendGetCollectionAction' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Controller/NFeedback/NFeedbackFrontendGetCollectionAction.php';

return $this->services['App\\Controller\\NFeedback\\NFeedbackFrontendGetCollectionAction'] = new \App\Controller\NFeedback\NFeedbackFrontendGetCollectionAction();
