<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.2BrqKKL.App\Entity\Partner' shared service.

$this->throw('Cannot autowire service ".service_locator.2BrqKKL": it references class "App\\Entity\\Partner" but no such service exists.');
