<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.BSBeG5J' shared service.

return $this->privates['.service_locator.BSBeG5J'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'ncomplimentTranslationRepository' => ['privates', 'App\\Repository\\NComplimentTranslationRepository', 'getNComplimentTranslationRepositoryService.php', true],
], [
    'ncomplimentTranslationRepository' => 'App\\Repository\\NComplimentTranslationRepository',
]);
