<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Ra.26FP' shared service.

return $this->privates['.service_locator.Ra.26FP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'ndaysRepository' => ['privates', 'App\\Repository\\NDaysRepository', 'getNDaysRepositoryService.php', true],
], [
    'ndaysRepository' => 'App\\Repository\\NDaysRepository',
]);
