<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\NLevelUrgency\NLevelUrgencyFrontendGetItemAction' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Controller/NLevelUrgency/NLevelUrgencyFrontendGetItemAction.php';

return $this->services['App\\Controller\\NLevelUrgency\\NLevelUrgencyFrontendGetItemAction'] = new \App\Controller\NLevelUrgency\NLevelUrgencyFrontendGetItemAction();
