<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.66H7zHR' shared service.

return $this->privates['.service_locator.66H7zHR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'ntaskTranslationRepository' => ['privates', 'App\\Repository\\NTaskTranslationRepository', 'getNTaskTranslationRepositoryService.php', true],
], [
    'ntaskTranslationRepository' => 'App\\Repository\\NTaskTranslationRepository',
]);
