<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.yTHyyKC' shared service.

return $this->privates['.service_locator.yTHyyKC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'ngoalsTranslationRepository' => ['privates', 'App\\Repository\\NGoalsTranslationRepository', 'getNGoalsTranslationRepositoryService.php', true],
], [
    'ngoalsTranslationRepository' => 'App\\Repository\\NGoalsTranslationRepository',
]);
