<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\NLevelUrgency\NLevelUrgencyFrontendGetCollectionAction' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Controller/NLevelUrgency/NLevelUrgencyFrontendGetCollectionAction.php';

return $this->services['App\\Controller\\NLevelUrgency\\NLevelUrgencyFrontendGetCollectionAction'] = new \App\Controller\NLevelUrgency\NLevelUrgencyFrontendGetCollectionAction();
