<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.jebCOMj' shared service.

return $this->privates['.service_locator.jebCOMj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'navailableTranslationRepository' => ['privates', 'App\\Repository\\NAvailableTranslationRepository', 'getNAvailableTranslationRepositoryService.php', true],
], [
    'navailableTranslationRepository' => 'App\\Repository\\NAvailableTranslationRepository',
]);
