<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.r0pIFds.App\Entity\Supervisor' shared service.

$this->throw('Cannot autowire service ".service_locator.r0pIFds": it references class "App\\Entity\\Supervisor" but no such service exists.');
