<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOXTbJZb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOXTbJZb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOXTbJZb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOXTbJZb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOXTbJZb\App_KernelDevDebugContainer([
    'container.build_hash' => 'OXTbJZb',
    'container.build_id' => '3baa9f7d',
    'container.build_time' => 1589918725,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOXTbJZb');
