<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6KWXLHw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6KWXLHw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6KWXLHw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6KWXLHw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6KWXLHw\App_KernelDevDebugContainer([
    'container.build_hash' => '6KWXLHw',
    'container.build_id' => 'c6c5596b',
    'container.build_time' => 1590353200,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6KWXLHw');
