<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWAB5XUG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWAB5XUG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWAB5XUG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWAB5XUG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWAB5XUG\App_KernelDevDebugContainer([
    'container.build_hash' => 'WAB5XUG',
    'container.build_id' => '9a728d52',
    'container.build_time' => 1590958929,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWAB5XUG');
